### GET all students
GET http://localhost:3000/api/students

### GET all students with `chris` in name
GET http://localhost:3000/api/students?search=chris

### GET all students with `stoph` in name
GET http://localhost:3000/api/students?search=stoph

### GET all students with `cel` in name
GET http://localhost:3000/api/students?search=cel

### GET all students with `e` in name
GET http://localhost:3000/api/students?search=e